project_metadata:
  package: web_tsp

global:
  environment: production
  engine.logging.on: true

controllers:
  '':
    controller: !!python/name:web_tsp.controller.Root
    /:
      tools.proxy.on: true
      tools.sessions.on: truetools.sessions.storage_type: memcached
      tools.staticdir.root: /home/wk/private/tsp/web_tsp/static
      tools.staticfile.root: /home/wk/private/tsp/web_tsp/static
    /css:
      tools.sessions.on: false
      tools.staticdir.on: true
      tools.staticdir.dir: css
    /js:
      tools.sessions.on: false
      tools.staticdir.on: true
      tools.staticdir.dir: js
    /img:
      tools.sessions.on: false
      tools.staticdir.on: true
      tools.staticdir.dir: img
    /favicon.ico:
      tools.sessions.on: false
      tools.staticfile.on: true
      tools.staticfile.filename: favicon.ico
  /api:
    controller: !!python/name:web_tsp.rest_controller.rest_controller
    /:
      request.dispatch: !!python/name:web_tsp.rest_controller.rest_controller
      tools.proxy.on: true
      error_page.default: !!python/name:web_tsp.rest_controller.generic_error_handler
      request.error_response: !!python/name:web_tsp.rest_controller.unexpected_error_handler



jinja2:
  loader: !!python/object:jinja2.loaders.FileSystemLoader
          encoding: utf-8
          searchpath: [/home/wk/private/tsp/web_tsp/src/web_tsp/templates]
  bytecode_cache: !!python/object:jinja2.bccache.FileSystemBytecodeCache {directory: /home/wk/private/tsp/web_tsp/.cache,
                                                                          pattern: __jinja2_%s.cache}
  auto_reload: false
  use_webassets: false